source "https://rubygems.org"

# Documentation tool versions
# These versions are managed centrally in docs/_data/versions.yml
# Update versions there to keep documentation dependencies in sync
# Note: For local development, use: bundle install --path vendor/bundle
#
# Version reference (see docs/_data/versions.yml):
# - jekyll: ~> 4.3
# - jekyll-sass-converter: ~> 2.0
# - just-the-docs: ~> 0.8.0
#
# Use Jekyll 4.3 with just-the-docs
# Force jekyll-sass-converter 2.x to avoid protobuf issues on macOS
gem "jekyll", "~> 4.3"

gem "jekyll-sass-converter", "~> 3.1"
gem "just-the-docs", "~> 0.10.1"


# Windows platform
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance and Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

