name: Build PR

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        include:
          - java-version: 17
            delay: 0
          - java-version: 21
            delay: 180
          - java-version: 25
            delay: 360
    uses: ./.github/workflows/build.yml
    with:
      javaVersion: "${{ matrix.java-version }}"
      delay: "${{ matrix.delay }}"
